use serde_json::json;
//this function creates  initial random data for  the wordchaser game
//this immitates a simple rest api for json respond
pub fn how_to_play_json() -> serde_json::Value {
  let playinfo = json!([
    {
      "info": "Start the Game",
      "description": "to start playing the game call »",
      "method": "near call word.onchez.testnet  random_word --accountId   Your accountId"
    },
     {
      "info": "To View if your guess is correct ",
      "description": "compares your guess to the random number generated by the user",
      "method": "near call word.onchez.testnet  check_solution word:you_solution --accountId   Your accountId"
    },
    {
      "info": "To check completed words ",
      "description": " this function views completed words",
      "method": "near call word.onchez.testnet  view_available_words --accountId   Your accountId"
    },
    {
      "info": "To view saved words ",
      "description": "view words that are saved on copletion ",
      "method": "near call word.onchez.testnet  view_saved --accountId   Your accountId"
    },
  {
      "info": "To add more turns in the game  ",
      "description": "adds the player more turns at  a cost of one near per  10 turns aded ",
      "method": "near call word.onchez.testnet add_more_turns --accountId   Your accountId"
    },
    {
      "info": "To get help",
      "description": "Know how to play this game",
      "method": "near call word.onchez.testnet  how_to_play --accountId   Your accountId"
    },

      ]);
  playinfo
}

//  _    _  _____ ______ ______  _____  _   _   ___   _____  _____ ______
// | |  | ||  _  || ___ \|  _  \/  __ \| | | | / _ \ /  ___||  ___|| ___ \
// | |  | || | | || |_/ /| | | || /  \/| |_| |/ /_\ \\ `--. | |__  | |_/ /
// | |/\| || | | ||    / | | | || |    |  _  ||  _  | `--. \|  __| |    /
// \  /\  /\ \_/ /| |\ \ | |/ / | \__/\| | | || | | |/\__/ /| |___ | |\ \
//  \/  \/  \___/ \_| \_||___/   \____/\_| |_/\_| |_/\____/ \____/ \_| \_|
